# Generated by Django 2.2.7 on 2019-11-13 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('colour', models.CharField(default=None, help_text='Please use the following format: <em>#00FF00</em>.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('colour', models.CharField(help_text='Please use the following format: <em>#00FF00</em>.', max_length=10)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('comment', models.TextField()),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subsection')),
            ],
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('definition', models.TextField()),
                ('comment', models.TextField()),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Word')),
            ],
        ),
        migrations.CreateModel(
            name='SubsectionTranslation',
            fields=[
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subsection')),
            ],
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section')),
            ],
        ),
    ]
