# Generated by Django 2.2.7 on 2019-11-23 08:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('code', models.CharField(help_text='Пример заполнения: <em>001</em>.', max_length=100, primary_key=True, serialize=False, verbose_name='Код раздела')),
                ('color', models.CharField(help_text='Пример заполнения: <em>#00FF00</em>.', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('code', models.CharField(help_text='Пример заполнения: <em>001001</em>.', max_length=100, primary_key=True, serialize=False, verbose_name='Код подраздела')),
                ('color', models.CharField(help_text='Пример заполнения: <em>#00FF00</em>. Для большей информации используйте таблицу цветов HTML', max_length=7, verbose_name='Цвет')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section', verbose_name='Выбрать/добавить раздел')),
            ],
            options={
                'verbose_name': 'Подраздел',
                'verbose_name_plural': 'Подразделы',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('code', models.CharField(help_text='Пример заполнения 1: <em>001001001</em>', max_length=100, primary_key=True, serialize=False, verbose_name='Код слова')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='картинка')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subsection', verbose_name='Выбрать/добавить подраздел')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish')], max_length=2, verbose_name='Выбрать язык')),
                ('name', models.CharField(help_text='Напишите перевод слова на выбранном языке', max_length=100, verbose_name='Перевод')),
                ('definition', models.TextField(help_text='Напишите определение слова на выбранном языке', verbose_name='Определение')),
                ('comment', models.TextField(help_text='Напишите комментарий слова на выбранном языке', verbose_name='Комментарий')),
                ('image_description', models.TextField(help_text='Пример заполнения: <em>объект изображения, время создания объекта, автор изображения, время создания изображения</em>', verbose_name='Описание картинки')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Word', verbose_name='Выбрать/добавить слово')),
            ],
            options={
                'verbose_name': 'Перевод слова',
                'verbose_name_plural': 'Переводы слов',
            },
        ),
        migrations.CreateModel(
            name='SubsectionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish')], max_length=2, verbose_name='Выбрать язык')),
                ('name', models.CharField(help_text='Напишите перевод подраздела на выбранном языке', max_length=100, verbose_name='Перевод')),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Subsection', verbose_name='Выбрать/добавить подраздел')),
            ],
            options={
                'verbose_name': 'Перевод подраздела',
                'verbose_name_plural': 'Переводы подразделов',
            },
        ),
        migrations.CreateModel(
            name='SectionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish')], max_length=2, verbose_name='Выбрать язык')),
                ('name', models.CharField(help_text='Напишите перевод раздела на выбранном языке', max_length=100, verbose_name='Перевод')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Section', verbose_name='Выбрать/добавить раздел')),
            ],
            options={
                'verbose_name': 'Перевод раздела',
                'verbose_name_plural': 'Переводы разделов',
            },
        ),
        migrations.CreateModel(
            name='CloseSenseWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_sense', models.ForeignKey(help_text='Choose from the list the close sense word', on_delete=django.db.models.deletion.CASCADE, related_name='close_sense', to='core.Word', verbose_name='Близкое по смыслу слово')),
                ('word', models.ForeignKey(help_text='Choose from the list the word', on_delete=django.db.models.deletion.CASCADE, related_name='word', to='core.Word', verbose_name='Исходное слово')),
            ],
            options={
                'verbose_name': 'Близкое по смыслу слово',
                'verbose_name_plural': 'Близкие по смыслу слова',
            },
        ),
    ]
