# Generated by Django 2.2.7 on 2019-11-19 15:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='word',
            name='image_description',
            field=models.TextField(help_text='Write the description of the picture', null=True),
        ),
        migrations.AddField(
            model_name='wordtranslation',
            name='image_description',
            field=models.TextField(help_text='Write the description translation of the picture', null=True),
        ),
        migrations.AlterField(
            model_name='closesenseword',
            name='close_sense',
            field=models.ForeignKey(help_text='Choose from the list the close sense word', on_delete=django.db.models.deletion.CASCADE, related_name='close_sense', to='core.Word'),
        ),
    ]
