# Generated by Django 2.2.7 on 2019-11-19 19:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191119_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='word',
            name='image_description',
            field=models.TextField(blank=True, help_text='Write the description of the picture', null=True),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='image_description',
            field=models.TextField(blank=True, help_text='Write the description translation of the picture', null=True),
        ),
    ]
