# Generated by Django 2.2.7 on 2019-11-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191123_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectiontranslation',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.Section', verbose_name='Выбрать/добавить раздел'),
        ),
        migrations.AlterUniqueTogether(
            name='sectiontranslation',
            unique_together={('section', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='subsectiontranslation',
            unique_together={('subsection', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='wordtranslation',
            unique_together={('word', 'language')},
        ),
    ]
