# Generated by Django 2.2.7 on 2020-03-05 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191124_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source',
            field=models.TextField(help_text='Напишите источник слова', null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='closesenseword',
            name='close_sense',
            field=models.ForeignKey(help_text='Choose from the list the close sense word', on_delete=django.db.models.deletion.CASCADE, related_name='word', to='core.Word', verbose_name='Близкое по смыслу слово'),
        ),
        migrations.AlterField(
            model_name='closesenseword',
            name='word',
            field=models.ForeignKey(help_text='Choose from the list the word', on_delete=django.db.models.deletion.CASCADE, related_name='close_senses', to='core.Word', verbose_name='Исходное слово'),
        ),
        migrations.AlterField(
            model_name='sectiontranslation',
            name='language',
            field=models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish'), ('PL', 'Polish'), ('JP', 'Japanese'), ('FA', 'Farsi'), ('AR', 'Arabic')], max_length=2, verbose_name='Выбрать язык'),
        ),
        migrations.AlterField(
            model_name='subsectiontranslation',
            name='language',
            field=models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish'), ('PL', 'Polish'), ('JP', 'Japanese'), ('FA', 'Farsi'), ('AR', 'Arabic')], max_length=2, verbose_name='Выбрать язык'),
        ),
        migrations.AlterField(
            model_name='subsectiontranslation',
            name='subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.Subsection', verbose_name='Выбрать/добавить подраздел'),
        ),
        migrations.AlterField(
            model_name='synonym',
            name='word',
            field=models.ForeignKey(help_text='Choose from the list the word', on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='core.WordTranslation', verbose_name='Исходное слово'),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='language',
            field=models.CharField(choices=[('BG', 'Bulgarian'), ('DE', 'German'), ('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('HR', 'Croatian'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('RO', 'Romanian'), ('RU', 'Russian'), ('TR', 'Turkish'), ('PL', 'Polish'), ('JP', 'Japanese'), ('FA', 'Farsi'), ('AR', 'Arabic')], max_length=2, verbose_name='Выбрать язык'),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.Word', verbose_name='Выбрать/добавить слово'),
        ),
        migrations.AlterUniqueTogether(
            name='closesenseword',
            unique_together={('word', 'close_sense')},
        ),
        migrations.AlterUniqueTogether(
            name='synonym',
            unique_together={('word', 'synonym')},
        ),
    ]
