# Generated by Django 2.2.7 on 2020-03-06 13:47

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200305_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='image_description',
            field=models.TextField(blank=True, help_text='Пример заполнения: <em>объект изображения, время создания объекта, автор изображения, время создания изображения</em>', null=True, verbose_name='Описание картинки'),
        ),
    ]
